//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditClinicAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditClinicAnswer()
        {
            this.RequiresImprovementActionPoints = new HashSet<RequiresImprovementActionPoint>();
            this.RequiresImprovementDetails = new HashSet<RequiresImprovementDetail>();
        }
    
        public int AuditClinicAnswersID { get; set; }
        public int AuditID { get; set; }
        public Nullable<int> Totalappointments { get; set; }
        public string ClinicCode { get; set; }
        public Nullable<int> NumberOfAppointmentsAllocated { get; set; }
        public Nullable<int> CaseNotesAvailableStartCount { get; set; }
        public Nullable<int> TemporaryNotesCount { get; set; }
        public Nullable<int> UnavailableCount { get; set; }
        public byte StatusID { get; set; }
        public bool IsActive { get; set; }
        public bool IsReviewed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequiresImprovementActionPoint> RequiresImprovementActionPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequiresImprovementDetail> RequiresImprovementDetails { get; set; }
    }
}
