//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int AuditID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int SpecialtyID { get; set; }
        public int SiteID { get; set; }
        public int CreatedByUserID { get; set; }
        public int CompletedByUserID { get; set; }
        public Nullable<System.DateTime> DueByDate { get; set; }
        public bool IsActive { get; set; }
    }
}
