//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Log()
        {
            this.LogDetails = new HashSet<LogDetail>();
        }
    
        public int LogID { get; set; }
        public byte ActionID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public System.DateTime LoggedTime { get; set; }
    
        public virtual LogAction LogAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogDetail> LogDetails { get; set; }
        public virtual LogSession LogSession { get; set; }
    }
}
