//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginRoleRight
    {
        public short RoleRightID { get; set; }
        public byte RoleID { get; set; }
        public short RightID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual LoginRight LoginRight { get; set; }
        public virtual LoginRole LoginRole { get; set; }
    }
}
