//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequiresImprovementDetail
    {
        public int RequiresImprovementDetailsID { get; set; }
        public string ClinicCode { get; set; }
        public Nullable<int> ImprovementReasonID { get; set; }
        public string Comment { get; set; }
        public int ReviewedByUserID { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
