//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnavailableCaseNote
    {
        public int UnavailableCaseNotesID { get; set; }
        public int AuditClinicAnswersID { get; set; }
        public string PatientDetails { get; set; }
        public int ReasonUnavailableID { get; set; }
        public bool IsActive { get; set; }
    }
}
